=== AlessandroMx/CreditSystem/credit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://itq.edu/soa/credit" targetNamespace="http://itq.edu/soa/credit" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="creditRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombres">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="([A-Za-z]+[\s]*)+"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="apellidoPaterno">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Za-z]+"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="apellidoMaterno">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Za-z]+"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="curp">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Z][A,E,I,O,U,X][A-Z]{2}[0-9]{2}[0-1][0-9][0-3][0-9][M,H][A-Z]{2}[B,C,D,F,G,H,J,K,L,M,N,Ã‘,P,Q,R,S,T,V,W,X,Y,Z]{3}[0-9,A-Z][0-9]"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="domicilio" type="xs:string"/>
				<xs:element name="salario" type="xs:double"/>
				<xs:element name="monto" type="xs:double"/>
				<xs:element name="tasaInteres" type="xs:double"/>
				<xs:element name="plazo" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="creditResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="autorizado" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AlessandroMx/CreditSystem/RegistroDeDatos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (x64) (http://www.altova.com)-->
<ns1:creditRequest xsi:schemaLocation="http://itq.edu/soa/credit credit.xsd" xmlns:ns1="http://itq.edu/soa/credit" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ns1:nombres>Luis Gerardo</ns1:nombres>
	<ns1:apellidoPaterno>Gomez</ns1:apellidoPaterno>
	<ns1:apellidoMaterno>Chavez</ns1:apellidoMaterno>
	<ns1:curp>VEGA780615HDFLML08</ns1:curp>
	<ns1:domicilio>vista bonita #109 col. villa del sol</ns1:domicilio>
	<ns1:correo>alessandromx@outlook.com</ns1:correo>
	<ns1:salario>15000</ns1:salario>
	<ns1:monto>760000</ns1:monto>
	<ns1:tasaInteres>.11</ns1:tasaInteres>
	<ns1:plazo>180</ns1:plazo>
</ns1:creditRequest>
